version: "3"
services:
  app:
    image: small_e_commerce
    container_name: small_e_commerce_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./.docker/app/php-fpm.ini:/user/local/etc/php/conf.d/99-app.ini
    links:
      - database
    depends_on:
      - database
    networks:
      - small_e_commerce_app_network

  nginx:
    image: nginx:alpine
    container_name: small_e_commerce_nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT}:80
    environment:
      NGINX_FPM_HOST: small_e_commerce_app
    networks:
      - small_e_commerce_app_network
    depends_on:
      - database
      - phpmyadmin

  database:
    container_name: small_e_commerce_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - small_e_commerce_app_network

  phpmyadmin:
    image: phpmyadmin
    container_name: small_e_commerce_phpmyadmin
    restart: always
    tty: true
    depends_on:
      - database
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
      networks:
        small_e_commerce_app_network

networks:
  small_e_commerce_app_network:
    driver: bridge
